### ISSUE TITLE
UtiLITI crashes when opening tmx maps created with new Tiled versions

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#185]
All I tried to do after clicking on "File>Create Project" was to select the folder in which I have my maps.

utiLITI directory: Workspace/Utilities/utiliti-v0.4.13-alpha-win/utiliti-v0.4.13-alpha.exe
maps directory: Workspace/Project/resources/maps/map_test.tmx

Here's the content of the crash.txt file. Hope it helps.

```
AWT-EventQueue-0 threw an exception:
java.lang.NullPointerException
	at de.gurkenlabs.utiliti.components.MapComponent.loadMaps(MapComponent.java:236)
	at de.gurkenlabs.utiliti.EditorScreen.create(EditorScreen.java:223)
	at de.gurkenlabs.utiliti.Program.lambda$initFileMenu$8(Program.java:424)
	at java.awt.MenuItem.processActionEvent(Unknown Source)
	at java.awt.MenuItem.processEvent(Unknown Source)
	at java.awt.MenuComponent.dispatchEventImpl(Unknown Source)
	at java.awt.MenuComponent.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by CalvinMT** [comment]
It crashes even when the map is in the utiLITI directory. Might be coming from the map file itself but I don't know why.

**Comment by CalvinMT** [comment]
I updated the map editor Tiled because I had an old version, but still no result.

**Comment by CalvinMT** [comment]
Ok, I've found the problem.
utiLITI can only open maps created with Tiled version 1.1.5.

Here's a link to all releases of Tiled, because they cannot be found on their official website.
Be sure to uninstall any other versions of Tiled before installing this one.
[https://github.com/bjorn/tiled/releases](url)

**Comment by nightm4re94** [comment]
You don't need to install an old Tiled version for this to work. It crashes because the new map's version attribute doesn't match the engine 's "maxSupportedVersion", which is a reminder that the engine may not support features from the latest Tiled versions. You can work around this by either changing the maxSupportedVersion or the map' s version manually.

**Comment by TheRamenChef** [comment]
And about that, it should really only log a warning, not throw an exception, because XML is designed to be extensible, i.e. an old program can still read some of the new format.

**Comment by nightm4re94** [comment]
That's true
