### ISSUE TITLE
Exception when saving in utiLITI

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine#252]
This is most likely related to the recent changes from #243.
Saving a utiLITI project results in the following exception:
```
Apr 14, 2019 1:41:45 AM de.gurkenlabs.litiengine.resources.ResourceBundle save
SEVERE: null
javax.xml.bind.MarshalException
 - with linked exception:
[com.sun.istack.SAXException2: A cycle is detected in the object graph. This will cause infinitely deep XML: de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset@325bc201 -> [-1, -1, -1, -1] -> de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset@325bc201]
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:301)
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95)
	at de.gurkenlabs.litiengine.resources.ResourceBundle.save(ResourceBundle.java:182)
	at de.gurkenlabs.utiliti.components.EditorScreen.saveGameFile(EditorScreen.java:649)
	at de.gurkenlabs.utiliti.components.EditorScreen.save(EditorScreen.java:598)
	at de.gurkenlabs.utiliti.Program.lambda$9(Program.java:436)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:811)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.SwingUtilities.processKeyBindings(SwingUtilities.java:1585)
	at javax.swing.UIManager$2.postProcessKeyEvent(UIManager.java:1483)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:846)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Followed by:

```
SEVERE: Game crashed! :(
java.lang.IndexOutOfBoundsException: Index: 7, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.getTile(Tileset.java:321)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.TilesetEntry.getImage(TilesetEntry.java:73)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tile.getImage(Tile.java:97)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.drawTile(MapRenderer.java:80)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.drawRow(MapRenderer.java:73)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.renderTileLayer(MapRenderer.java:61)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.renderLayers(MapRenderer.java:35)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.render(MapRenderer.java:23)
	at de.gurkenlabs.litiengine.environment.Environment.render(Environment.java:1191)
	at de.gurkenlabs.litiengine.environment.Environment.render(Environment.java:1020)
	at de.gurkenlabs.utiliti.components.EditorScreen.render(EditorScreen.java:134)
	at de.gurkenlabs.litiengine.graphics.RenderComponent.render(RenderComponent.java:157)
	at de.gurkenlabs.litiengine.RenderLoop.process(RenderLoop.java:25)
	at de.gurkenlabs.litiengine.UpdateLoop.run(UpdateLoop.java:46)
```

**Comment by steffen-wilke** [comment]
Perfect! @TheRamenChef  thank you :)

**Comment by steffen-wilke** [comment]
Not exactly sure if it's related to this issue or the PR but the XML now has a lot of `tile` elements that were previously not serialized. This results in an overall size increase of around 50% for the `.litidata` file of [Gurk Nukem](https://github.com/gurkenlabs/litiengine-gurk-nukem). We should prevent this.

**Comment by steffen-wilke** [comment]
I now get the following error again:
```
SEVERE: Game crashed! :(
java.lang.IndexOutOfBoundsException: Index: 16, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.getTile(Tileset.java:326)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.getTile(Tileset.java:319)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.TmxMap.getTilesetEntry(TmxMap.java:207)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.TileLayer.finish(TileLayer.java:104)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.TmxMap.finish(TmxMap.java:297)
	at de.gurkenlabs.litiengine.resources.ResourceBundle.load(ResourceBundle.java:103)
	at de.gurkenlabs.litiengine.resources.ResourceBundle.load(ResourceBundle.java:83)
	at de.gurkenlabs.utiliti.components.EditorScreen.load(EditorScreen.java:307)
	at de.gurkenlabs.utiliti.Program.main(Program.java:47)
```

**Comment by TheRamenChef** [comment]
Whoops, forgot to update references. Does it work now?

**Comment by steffen-wilke** [comment]
With these recent changes, I get the following error:
```
Apr 14, 2019 8:17:00 PM de.gurkenlabs.litiengine.resources.ResourceBundle load
SEVERE: null
javax.xml.bind.UnmarshalException
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:714)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleError(UnmarshallingContext.java:741)
	at com.sun.xml.bind.v2.runtime.JaxBeanInfo.invokeUnmarshallCallback(JaxBeanInfo.java:541)
	at com.sun.xml.bind.v2.runtime.JaxBeanInfo.invokeAfterUnmarshalMethod(JaxBeanInfo.java:532)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.fireAfterUnmarshal(Loader.java:203)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.leaveElement(StructureLoader.java:267)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:573)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:150)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
	at de.gurkenlabs.litiengine.util.io.XmlUtilities.readFromFile(XmlUtilities.java:94)
	at de.gurkenlabs.litiengine.resources.ResourceBundle.getGameFileFromFile(ResourceBundle.java:207)
	at de.gurkenlabs.litiengine.resources.ResourceBundle.load(ResourceBundle.java:88)
	at de.gurkenlabs.litiengine.resources.ResourceBundle.load(ResourceBundle.java:83)
	at de.gurkenlabs.utiliti.components.EditorScreen.load(EditorScreen.java:307)
	at de.gurkenlabs.utiliti.Program.main(Program.java:47)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.xml.bind.v2.runtime.JaxBeanInfo.invokeUnmarshallCallback(JaxBeanInfo.java:537)
	... 27 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 7, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.getTerrain(Tileset.java:257)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.updateTileTerrain(Tileset.java:359)
	at de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.afterUnmarshal(Tileset.java:371)
	... 32 more
```

@TheRamenChef btw: You can use the [Gurk Nukem](https://github.com/gurkenlabs/litiengine-gurk-nukem) project and open it up in the utiLITI editor to test whether this is fixed.

**Comment by TheRamenChef** [comment]
I opened that project in my latest commit, modified it, saved it, and it didn't seem to have any problems. I think I fixed it.

**Comment by steffen-wilke** [comment]
Seems to be fixed. Thank's again! :)
