### ISSUE TITLE
Crash on loadEnvironment, illegal char <:> in path

### ISSUE THREAD

**Issue by Max-Hollywood** [gurkenlabs/litiengine#334]
I've only just tried litiengine today, but the one crash I can't get past is:

> Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\E:\workspaces\eclipse\java\knightslide\src\pft\knightslide\resources\tiles\simpletiles.tsx

when calling

> Game.world().loadEnvironment("src/resources/maps/map01.tmx");

It looks like it's trying to find "file:\E:\" instead of just "E:\".

I've tried using the file name and the "map name", but Windows is looking for that file that isn't there.

It's successful in loading the `game.litidata`.

Full stack (I think `WARNING: Tiled version 1.3.3 of map "null" is greater than the supported version 1.2.x. Some features may not work.` might be an issue, but I can't find utiLITI previous versions, as the only link to it was some vague place in the docs).

**Comment by TheRamenChef** [comment]
Do you have the full stack trace?

**Comment by Max-Hollywood** [comment]
Oops I knew I forgot something:

Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.environment.tilemap.xml.TmxMap checkVersion
WARNING: Tiled version 1.3.3 of map "p_map01" is greater than the supported version 1.2.x. Some features may not work.
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: 1 maps loaded from file:/E:/workspaces/eclipse/java/knightslide/src/pft/knightslide/resources/game.litidata
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: 0 blueprints loaded from file:/E:/workspaces/eclipse/java/knightslide/src/pft/knightslide/resources/game.litidata
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: 1 tilesets loaded from file:/E:/workspaces/eclipse/java/knightslide/src/pft/knightslide/resources/game.litidata
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: 1 spritesheets loaded from file:/E:/workspaces/eclipse/java/knightslide/src/pft/knightslide/resources/game.litidata
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: 0 sounds loaded from file:/E:/workspaces/eclipse/java/knightslide/src/pft/knightslide/resources/game.litidata
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: 4 sprites loaded to memory
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.resources.Resources load
INFO: loading game resources from file:/E:/workspaces/eclipse/java/knightslide/src/pft/knightslide/resources/game.litidata took 358.684 ms
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.configuration.Configuration load
INFO: Configuration config.properties loaded
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.environment.tilemap.xml.TmxMap checkVersion
WARNING: Tiled version 1.3.3 of map "null" is greater than the supported version 1.2.x. Some features may not work.
Apr 10, 2020 1:42:16 AM de.gurkenlabs.litiengine.DefaultUncaughtExceptionHandler uncaughtException
SEVERE: Game crashed! :(
de.gurkenlabs.litiengine.resources.ResourceLoadException: de.gurkenlabs.litiengine.resources.ResourceLoadException: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\E:\workspaces\eclipse\java\knightslide\src\pft\knightslide\resources\tiles\simpletiles.tsx
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.loadResource(ResourcesContainer.java:391)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:273)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:207)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.environment.GameWorld.getEnvironment(GameWorld.java:315)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.environment.GameWorld.loadEnvironment(GameWorld.java:420)
	at knightslide/pft.knightslide.KnightSlide.main(KnightSlide.java:47)
Caused by: de.gurkenlabs.litiengine.resources.ResourceLoadException: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\E:\workspaces\eclipse\java\knightslide\src\pft\knightslide\resources\tiles\simpletiles.tsx
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.loadResource(ResourcesContainer.java:391)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:273)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:278)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:211)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.environment.tilemap.xml.Tileset.finish(Tileset.java:208)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.environment.tilemap.xml.TmxMap.finish(TmxMap.java:305)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.Maps.load(Maps.java:37)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.Maps.load(Maps.java:15)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.loadResource(ResourcesContainer.java:389)
	... 6 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\E:\workspaces\eclipse\java\knightslide\src\pft\knightslide\resources\tiles\simpletiles.tsx
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/jdk.internal.module.Resources.toSafeFilePath(Resources.java:143)
	at java.base/jdk.internal.module.Resources.toFilePath(Resources.java:97)
	at java.base/jdk.internal.module.ModuleReferences$ExplodedModuleReader.find(ModuleReferences.java:382)
	at java.base/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:428)
	at java.base/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:423)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findMiscResource(BuiltinClassLoader.java:422)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:309)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1400)
	at java.base/java.lang.ClassLoader.getSystemResource(ClassLoader.java:1665)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.Resources.getLocation(Resources.java:338)
	at litiengine@0.4.20/de.gurkenlabs.litiengine.resources.ResourcesContainer.loadResource(ResourcesContainer.java:389)
	... 15 more

**Comment by Max-Hollywood** [comment]
I think the problem is _where_ I am keeping these resources.  After sleep, sugar and caffeine, I tried again, going through the litiengine tabs, and this caught my eye:

> If the file is located in your game’s root folder, then you only have to specify the name. If the file is not in your game’s directory, then you have to specify the full path. (https://litiengine.com/litiengine-tutorial-creating-an-arkanoid-game/)

Inconsistent phrasing is confusing me there, is "game's directory == game's root folder"?  If it is, then specifying the full path is what caused the crash.

Which looks like it coincides with the "recommended" project layout as mentioned in the docs (https://docs.litiengine.com/basics/getting-started).

So I re-created the maps and the data file (moving the resources around messes with their internal paths), moved them to where the doc suggested, and it seems to work now.  Data file in the root directory, and the maps in their own folder in the root directory.

It still complains about Tiled maps being higher than the supported version, but that's beyond where I'm up to right now.

**Comment by TheRamenChef** [comment]
That tutorial is wrong: the game doesn't load resources from the game directory; it loads them from the *classpath*, which is generally the game directory in a developer environment. Also, the game complaining about the Tiled version is most likely because you're using Tiled 1.3, which the engine doesn't support yet.

Anyway, since this issue seems to have resolved itself, I'm going to go ahead and close it.
