### ISSUE TITLE
Exception when removing maps from project

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#338]
```java
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1009)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:963)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.renderLayers(MapRenderer.java:78)
	at de.gurkenlabs.litiengine.environment.tilemap.MapRenderer.render(MapRenderer.java:74)
	at de.gurkenlabs.litiengine.environment.Environment.render(Environment.java:2069)
	at de.gurkenlabs.litiengine.environment.Environment.render(Environment.java:1911)
	at de.gurkenlabs.utiliti.components.Editor.render(Editor.java:129)
	at de.gurkenlabs.litiengine.graphics.RenderComponent.render(RenderComponent.java:123)
	at de.gurkenlabs.litiengine.GameLoop.process(GameLoop.java:87)
	at de.gurkenlabs.litiengine.UpdateLoop.run(UpdateLoop.java:57)
```

**Comment by TheRamenChef** [comment]
Something in another thread modified the layers on a map while it was being drawn. I don't think this has anything to do with removing maps.
