### ISSUE TITLE
utiLITI bugging from opening 64x64 tiled map

### ISSUE THREAD

**Issue by MAAMichaud** [gurkenlabs/litiengine#404]
**Describe the bug**
Loading a map with 64x64 tiles causes utiLITI to bug out and lose the ability to properly load functioning maps.

**Stack Trace**
The error message you get either in your console or the `crash.txt` located in your program's root directory.
```
WARNING   Tiled version 1.6.0 of map "null" is greater than the supported version 1.2.x. Some features may not work.
INFO      map found: dungeonMap
INFO      map found: level1
INFO      1 tilesets loaded from dungeonMap
INFO      1 tilesets loaded from level1
SEVERE    java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at de.gurkenlabs.litiengine.util.Imaging.getCompatibleImage(Imaging.java:339)
	at de.gurkenlabs.utiliti.renderers.GridRenderer$GridImages.createImage(GridRenderer.java:91)
	at de.gurkenlabs.utiliti.renderers.GridRenderer$GridImages.<init>(GridRenderer.java:74)
	at de.gurkenlabs.utiliti.renderers.GridRenderer$GridImages.<init>(GridRenderer.java:60)
	at de.gurkenlabs.utiliti.renderers.GridRenderer.render(GridRenderer.java:38)
	at de.gurkenlabs.utiliti.renderers.Renderers.render(Renderers.java:25)
	at de.gurkenlabs.utiliti.components.MapComponent.render(MapComponent.java:201)
	at de.gurkenlabs.litiengine.gui.GuiComponent.render(GuiComponent.java:733)
	at de.gurkenlabs.utiliti.components.Editor.render(Editor.java:151)
	at de.gurkenlabs.litiengine.graphics.RenderComponent.render(RenderComponent.java:123)
	at de.gurkenlabs.litiengine.GameLoop.process(GameLoop.java:92)
	at de.gurkenlabs.litiengine.UpdateLoop.run(UpdateLoop.java:57)
```

**To Reproduce**
1. Create a 64x64 tileset png in paint
2. Generate a 64x64 tileset file in Tiled map editor from the png
3. Create a small map based on this tileset in Tiled map editor
4. Import this map in utiLITI

**Expected behavior**
Either the ability to handle 64x64 tiled maps, or the ability to continue using the program after the map loading failure.

**Screenshots**
64x64 map failing to load
![image](https://user-images.githubusercontent.com/68875170/118978435-b2e67480-b94d-11eb-9e76-e51166d051d8.png)

utiLITI unable to display Gurk Nukem level1 after the bug
![image](https://user-images.githubusercontent.com/68875170/118978491-c691db00-b94d-11eb-8e4d-30d102bd4aaf.png)

**Your System:**
 - OS: Windows 10
 - LITIENGINE version: 0.5.1-beta.exe
 - Java JDK/JRE version: JDK 1.8
 - Screen resolution: 1920x1080

**Additional context**
The problem went away with 8x8, 16x16, and 32x32 versions of the same map. The map was modified with a text editor to only change the tile size to narrow down the problem. No other aspect of the map seems to have caused any issues.

**Comment by steffen-wilke** [comment]
#428
