### ISSUE TITLE
Sound import bug in utiLITI.exe

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#405]
**Describe the bug**
The executable version of utiLITI is unable to import sounds.

**Stack Trace**

```java
SEVERE: The audio file santa-laugh2 could not be loaded.
May 28, 2021 7:20:13 PM de.gurkenlabs.utiliti.components.Editor importSounds
SEVERE: could not get audio input stream from input stream
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input stream
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at de.gurkenlabs.litiengine.sound.Sound.<init>(Sound.java:51)
	at de.gurkenlabs.litiengine.resources.SoundResource.<init>(SoundResource.java:33)
	at de.gurkenlabs.utiliti.components.Editor.importSounds(Editor.java:457)
	at de.gurkenlabs.utiliti.components.Editor.importSounds(Editor.java:385)
	at de.gurkenlabs.utiliti.swing.menus.ResourcesMenu.lambda$new$7(ResourcesMenu.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at com.github.weisj.darklaf.ui.menu.DarkMenuItemUIBase.doClick(DarkMenuItemUIBase.java:257)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**To Reproduce**
1. Download `utiliti-v0.5.1-beta.exe`
2. Click on 'Resources -> Import Sounds...'
3. Double-click an audio file (I tried with .ogg)

**Expected behavior**
The sound should be loaded and added to the game resources.

**Your System:**
 - OS: Win10
 - LITIENGINE version: 0.5.1-beta SDK
 - Java JDK/JRE version: AdoptOpenJDK (build 13.0.2+8)

**Additional context**
There might be something wrong with how we bundle native libraries when releasing.

**Comment by weisJ** [comment]
Using the jpackage build from #413 sounds can be imported just fine

**Comment by steffen-wilke** [comment]
Closing since #413 should fix the issue.
