### ISSUE TITLE
Utiliti built with JPackage does not launch

### ISSUE THREAD

**Issue by Gamebuster19901** [gurkenlabs/litiengine#426]
**Describe the bug**
There are missing resources required to launch Utiliti. For example: the desktop icon `liti-logo-x16`

**Stack Trace**
```java
Fri Nov 12 02:36:57 PST 2021 AWT-EventQueue-0 threw an exception:
de.gurkenlabs.utiliti.UtiLITIInitializationError: UtiLITI failed to initialize, see the stacktrace below for more information
	at de.gurkenlabs.utiliti.Program.lambda$main$1(Program.java:45)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: de.gurkenlabs.litiengine.resources.ResourceLoadException: javax.imageio.IIOException: Can't get input stream from URL!
	at de.gurkenlabs.litiengine.resources.ResourcesContainer.loadResource(ResourcesContainer.java:391)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:273)
	at de.gurkenlabs.litiengine.resources.ResourcesContainer.get(ResourcesContainer.java:207)
	at de.gurkenlabs.litiengine.Game.init(Game.java:485)
	at de.gurkenlabs.utiliti.Program.lambda$main$1(Program.java:34)
	... 13 more
Caused by: javax.imageio.IIOException: Can't get input stream from URL!
	at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
	at de.gurkenlabs.litiengine.resources.Images.load(Images.java:49)
	at de.gurkenlabs.litiengine.resources.Images.load(Images.java:12)
	at de.gurkenlabs.litiengine.resources.ResourcesContainer.loadResource(ResourcesContainer.java:389)
	... 18 more
Caused by: java.io.FileNotFoundException: C:\Users\ronan\litiengine\build\litiengine-utiliti\jpackage\litiengine-utiliti\liti-logo-x16.png (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	... 22 more

====Runtime Information====
Operating System: Windows 10
	Architecture: amd64
	Version: 10.0
Memory:
	Max heap size: 1.0 GiB
	Current heap size: 256.0 MiB
	Heap used: 6.3 MiB
	Free heap: 249.7 MiB
Java Version: OpenJDK Runtime Environment 16.0.2+7 
	Vendor: Eclipse Foundation
Uptime: PT2.3S
Screens: 2
	Screen 0: 1920x1080@60hz
	Screen 1: 1920x1080@60hz
```

**To Reproduce**
1. `./gradlew jpackage`
2. run utiiliti

**Expected behavior**
Utiliti should launch

**Screenshots**
![image](https://user-images.githubusercontent.com/7155747/141455992-e63bab82-9367-4948-91d7-d9d16dfa4e25.png)

**Your System:**
 - LITIENGINE version: Commit c9d2e4ed7cae791883c16e017bcfb19e0f8af06e

**Additional context**
Unreleased version of LitiEngine/Utiliti

**Comment by steffen-wilke** [comment]
Fixed with 
885824c5be4450dab69e64df7af8f99d5c97c765
