### ISSUE TITLE
utiLITI opens as a blank window (Mac)

### ISSUE THREAD

**Issue by EdwardAndress** [gurkenlabs/litiengine#427]
**Describe the bug**
When I execute `utiliti-v0.5.1-beta.jar` the application appears to start but hangs after opening a blank window.

**Stack Trace**

```java
Sun Nov 14 12:07:08 GMT 2021 AWT-EventQueue-0 threw an exception:
java.lang.IllegalAccessError: class com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge (in unnamed module @0x1796cf6c) cannot access class sun.swing.DefaultLookup (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x1796cf6c
	at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge.getInputMap(DarkTabbedPaneUIBridge.java:860)
	at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge.installKeyboardActions(DarkTabbedPaneUIBridge.java:782)
	at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge.installUI(DarkTabbedPaneUIBridge.java:228)
	at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUI.installUI(DarkTabbedPaneUI.java:129)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:730)
	at java.desktop/javax.swing.JTabbedPane.setUI(JTabbedPane.java:249)
	at java.desktop/javax.swing.JTabbedPane.updateUI(JTabbedPane.java:265)
	at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:227)
	at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:192)
	at de.gurkenlabs.utiliti.swing.UI.initBottomPanel(UI.java:279)
	at de.gurkenlabs.utiliti.swing.UI.initRenderSplitPanel(UI.java:230)
	at de.gurkenlabs.utiliti.swing.UI.setupInterface(UI.java:181)
	at de.gurkenlabs.utiliti.swing.UI.init(UI.java:121)
	at de.gurkenlabs.utiliti.Program.lambda$main$1(Program.java:40)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**To Reproduce**

Download the latest LITIEngine on a macbook pro and try to open the `utiliti-v0.5.1-beta.jar`

**Expected behavior**
I had hoped to see the screen shown on this page: https://litiengine.com/docs/utiliti-editor/

**Screenshots**

<img width="1438" alt="Screenshot 2021-11-14 at 12 23 43" src="https://user-images.githubusercontent.com/7963978/141680893-43c480d0-4903-4cfc-808a-832c046fc2e4.png">

**Your System:**
 - OS: BigSur 11.0.1
 - LITIENGINE version: 0.5.1-beta
Java version
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Additional context**
I assume I am doing something silly :)

**Comment by weisJ** [comment]
This is the same issue as #406. See there for possible solutions.

**Comment by EdwardAndress** [comment]
OK, thanks @weisJ 👍

**Comment by EdwardAndress** [comment]
Should I be adding further comments here, or on the other issue, @weisJ?

**Comment by nightm4re94** [comment]
Please comment on #406, I will close this as duplicate.
